interface EnvConfig {
  apiKey: string;
  model: string;
  provider?: string;
  dashboardPort: number;
  gatewayPort?: number;
  publicUrl?: string;
}

export function generateEnv(config: EnvConfig): string {
  const lines: string[] = [
    "# Company Agents Environment Configuration",
    "# Generated by create-company-agents",
    "",
    `LLM_API_KEY="${config.apiKey.replace(/"/g, '\\"')}"`,
    `LLM_PROVIDER="${config.provider ?? "openrouter"}"`,
    `DEFAULT_MODEL="${config.model.replace(/"/g, '\\"')}"`,
    `DASHBOARD_PORT=${config.dashboardPort}`,
    `GATEWAY_PORT=${config.gatewayPort ?? 42617}`,
  ];

  if (config.publicUrl) {
    lines.push(`PUBLIC_URL="${config.publicUrl.replace(/"/g, '\\"')}"`);
  }

  lines.push("");
  return lines.join("\n");
}
