interface EnvConfig {
  apiKey: string;
  model: string;
  dashboardPort: number;
  publicUrl?: string;
}

export function generateEnv(config: EnvConfig): string {
  const lines: string[] = [
    "# HermesOps Environment Configuration",
    "# Generated by create-hermesops",
    "",
    `LLM_API_KEY=${config.apiKey}`,
    `DEFAULT_MODEL=${config.model}`,
    `DASHBOARD_PORT=${config.dashboardPort}`,
  ];

  if (config.publicUrl) {
    lines.push(`PUBLIC_URL=${config.publicUrl}`);
  }

  lines.push("");
  return lines.join("\n");
}
