interface EnvConfig {
  apiKey: string;
  model: string;
  dashboardPort: number;
  publicUrl?: string;
}

export function generateEnv(config: EnvConfig): string {
  const lines: string[] = [
    "# HermesOps Environment Configuration",
    "# Generated by create-hermesops",
    "",
    `LLM_API_KEY="${config.apiKey.replace(/"/g, '\\"')}"`,
    `DEFAULT_MODEL="${config.model.replace(/"/g, '\\"')}"`,
    `DASHBOARD_PORT=${config.dashboardPort}`,
  ];

  if (config.publicUrl) {
    lines.push("# For VPS deployments, update PUBLIC_URL to your domain after running 'deploy'");
    lines.push(`PUBLIC_URL="${config.publicUrl.replace(/"/g, '\\"')}"`);
  }

  lines.push("");
  return lines.join("\n");
}
